name = "ResComp"
uuid = "5e056418-07d4-4936-a843-989fc06f8afb"
authors = "Taylor Pool taylorpool.27@gmail.com"
version = "1.0.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
